// AccessiScan GitHub App client for Auto-Fix PRs.
//
// We use a GitHub App (not OAuth user tokens) so customers install on their
// org once and we can act with installation-scoped tokens — no per-user
// re-auth, no refresh-token expiration to manage.
//
// Setup steps (one-time, by us):
// 1. Create a GitHub App at https://github.com/settings/apps/new
//    Name: "AccessiScan Auto-Fix"
//    Homepage: https://accessiscan.piposlab.com
//    Callback URL: https://accessiscan.piposlab.com/api/github-app/callback
//    Webhook URL: (leave blank for MVP — we trigger fixes on user action)
//    Permissions:
//      - Repository: Contents read+write, Pull requests read+write, Metadata read
//      - Account: (none)
//    Where can it be installed: Any account
// 2. Generate a private key (.pem), download it.
// 3. Add to Vercel envs:
//    GITHUB_APP_ID, GITHUB_APP_PRIVATE_KEY (paste the .pem contents),
//    GITHUB_APP_CLIENT_ID, GITHUB_APP_CLIENT_SECRET, GITHUB_APP_NAME

import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";

function appId(): number {
  const v = process.env.GITHUB_APP_ID;
  if (!v) throw new Error("GITHUB_APP_ID not configured");
  return Number(v);
}

function privateKey(): string {
  const v = process.env.GITHUB_APP_PRIVATE_KEY;
  if (!v) throw new Error("GITHUB_APP_PRIVATE_KEY not configured");
  // Vercel stores newlines as \n literal — restore them.
  return v.replace(/\\n/g, "\n");
}

/**
 * App-level authenticated Octokit. Use only for app-scoped endpoints
 * (listing installations, creating installation tokens, etc.).
 */
export function appOctokit(): Octokit {
  return new Octokit({
    authStrategy: createAppAuth,
    auth: { appId: appId(), privateKey: privateKey() },
  });
}

/**
 * Installation-scoped Octokit. Use for actual repo operations (read files,
 * commit, open PR). The installation_id comes from the
 * `github_installations` table.
 */
export function installationOctokit(installationId: number): Octokit {
  return new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: appId(),
      privateKey: privateKey(),
      installationId,
    },
  });
}

/**
 * Open an auto-fix PR with one or more file patches.
 *
 * Strategy:
 *   1. Get the default branch SHA (head).
 *   2. Create a new branch off head: `accessiscan/fix-{scanId}-{timestamp}`.
 *   3. For each patch: get current file blob, write new content, create commit.
 *   4. Open PR from new branch → default branch.
 *
 * Returns the PR URL + number.
 */
export async function openAutoFixPR(opts: {
  installationId: number;
  owner: string;
  repo: string;
  scanId: string;
  patches: Array<{
    file_path: string;
    new_content: string;
    rule: string;
    issue_id: string;
    summary: string;
  }>;
  prTitle: string;
  prBody: string;
}): Promise<{ pr_url: string; pr_number: number; branch: string }> {
  const octokit = installationOctokit(opts.installationId);
  const { owner, repo } = opts;

  // 1. Default branch + head SHA.
  const { data: repoInfo } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoInfo.default_branch;
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const headSha = refData.object.sha;

  // 2. New branch.
  const branch = `accessiscan/fix-${opts.scanId}-${Date.now()}`;
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branch}`,
    sha: headSha,
  });

  // 3. Patches as a single commit using the Tree API (atomic).
  const treeItems: Array<{
    path: string;
    mode: "100644";
    type: "blob";
    sha: string;
  }> = [];
  for (const patch of opts.patches) {
    const { data: blob } = await octokit.git.createBlob({
      owner,
      repo,
      content: Buffer.from(patch.new_content, "utf-8").toString("base64"),
      encoding: "base64",
    });
    treeItems.push({
      path: patch.file_path,
      mode: "100644",
      type: "blob",
      sha: blob.sha,
    });
  }
  const { data: newTree } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: headSha,
    tree: treeItems,
  });
  const { data: newCommit } = await octokit.git.createCommit({
    owner,
    repo,
    message: `Accessibility: ${opts.prTitle}\n\nGenerated by AccessiScan Auto-Fix.`,
    tree: newTree.sha,
    parents: [headSha],
  });
  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branch}`,
    sha: newCommit.sha,
  });

  // 4. Open the PR.
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: opts.prTitle,
    body: opts.prBody,
    head: branch,
    base: defaultBranch,
  });
  // Tag with a label so customers can filter their inbox.
  try {
    await octokit.issues.addLabels({
      owner,
      repo,
      issue_number: pr.number,
      labels: ["accessibility", "accessiscan-auto-fix"],
    });
  } catch {
    // labels are optional; if the repo doesn't have them, ignore.
  }

  return { pr_url: pr.html_url, pr_number: pr.number, branch };
}

/**
 * Fetch a file's current content from the repo at a specific ref. Returns
 * decoded UTF-8 text. Used by the patch generator to read the original code
 * before sending it to Claude.
 */
export async function getFileContent(
  installationId: number,
  owner: string,
  repo: string,
  filePath: string,
  ref?: string,
): Promise<string> {
  const octokit = installationOctokit(installationId);
  const { data } = await octokit.repos.getContent({
    owner,
    repo,
    path: filePath,
    ref,
  });
  if (Array.isArray(data) || data.type !== "file" || !("content" in data)) {
    throw new Error(`Path ${filePath} is not a file`);
  }
  return Buffer.from(data.content, "base64").toString("utf-8");
}
